name: Build Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build Docker Image and Push to GHCR, Docker Hub, or AWS ECR
      uses: GlueOps/github-actions-build-push-containers@v0.4.1
      with:
        tags: $(date +%s), latest
          
